# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

###############################################################################
###                           Faucet Configuration                            ###
###############################################################################

[ui]
port = 1314

[faucet]
# account_prefix for bech32 encoding
account_prefix="ethm"
# env_prefix for storing the all env variables
env_prefix="ETHERMINT"
# amount is tokens per request
amount = 10000
# maximum tokens allowed for an account
max_tokens = 10000000
# tendermint node address
# <host>:<port> to Tendermint RPC interface for this chain
node = "tcp://localhost:26657"
# chain denom
denom = "aphoton"

